[package]
name = "antimalware-service"
version = "0.1.0"
edition = "2021"
default-run = "main"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
custom_error = "1.9.2"
named_pipe = "0.4.1"
windows = "0.48.0"
windows-service = "0.6.0"
windows-sys = { version = "0.48.0", features = ["Win32_Foundation"] }
